### ISSUE TITLE
Problems importing the addon

### ISSUE THREAD

**Issue by WetwarePrometheus** [hsab/UMOG#2]
Sorry to bother you @micahjohnston, @mp4, @hsab and @jacobcluke, but I tried importing this addon and I got this error message:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\addon_utils.py", line 330, in enable
    mod = __import__(module_name)
  File "C:\Users\barti\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UMOG-master\__init__.py", line 37, in <module>
    from .umog_addon import import_modules
  File "C:\Users\barti\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UMOG-master\umog_addon\__init__.py", line 119, in <module>
    UMOGCreateMenus()
  File "C:\Users\barti\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\UMOG-master\umog_addon\__init__.py", line 106, in UMOGCreateMenus
    "UMOGMenu%s" % menu["text"],
TypeError: string indices must be integers`
I tried using a newer version of blender and it gave me an error message about pyximport missing. I'm afraid I don't understand what the problem might be and if it's just me, what do you think?

**Comment by mp4** [comment]
The master branch of the plugin currently is using cython and requires the installation of some dependencies.(this may be a bit tricky but is documented [https://github.com/hsab/UMOG/wiki/Development](here) ) I recently created a release that should be able to just be downloaded and installed as usual [https://github.com/hsab/UMOG/releases](link) on Blender 2.79. I also added a page documenting how to get started with the reaction diffusion system [https://github.com/hsab/UMOG/wiki/Reaction-Diffusion-Node](here). Let me know if this still isn't working for you.
